# Gold tools configuration v1.6 
# The source is what the player needs in there inventory in order to convert their tool
# The item is the item id of the item needed to convert, its the "source" item.
# The amount is how many of the items they need to convert.
# The item is not taken after conversion attempts, probably make it hard to get.
# To disable this, simply set the item to 0 and the amount to 0.
# Default source is 10 gold ingots. Change it to whatever you like.
# To disable the mining of the block below, change false to true.
# Tool damage is the damage dealt to a gold pick when a player instant mines a ore 
# Tool damage must be at least 1 or the pick would not die if you only mined ores
# For more help on configuration, visit the bukkit dev page.
# ore = lapis, gold, iron, or redstone ore.
# precious = gold, iron, lapis blocks. 
Source:
  item: 266
  amount: 10
disable:
  mine:
    ironore: false
    goldore: false
    lapisore: false
    redstoneore: false
    ironblock: true
    goldblock: true
    lapisblock: true
mine:
  ore:
    tooldamage: 2
  precious:
    tooldamage: 2