# McLevelUp Configuration
# Currently there is nothing to configure
# Nor are the configuration classes implemented yet, if there is something you would like to customize in this plugin. Please suggest on the bukkit dev project page. thanks