name: Goldtools
version: 2.1
description: Golden tools re imagined!
author: milkywayz 
website: http://milkycraft.net

main: net.milkycraft.Goldtools
softdepend: [WorldGuard, Vault, LogBlock]

commands:
    goldtools:
      description: View info on this plugin
      aliases: gt ription: View info on this plugin
      aliases: gt 