name: Goldtools
version: 2.0
description: Golden tools re imagined!
author: milkywayz 
website: http://milkycraft.net

main: net.milkycraft.Goldtools
softdepend: [WorldGuard, Vault, LogBlock]

commands:
    gold:
      description: Convert tools to gold!
    goldtools:
      description: View info on this plugin
      aliases: gt 