name: GoldTools
author: milkywayz 
main: net.milkycraft.Goldtools
description: Convert wood tools to gold easily!
website: http://milkycraft.net
version: 1.3

commands:
    gold:
      description: Convert tools to gold!
    goldtools:
      description: View info on this plugin