# Gold tools configuration v1.9
# source is the item you need in your inventory to use /gold , set amount to 0 to disable.
# You can disable the mining of some blocks if you want
# You can set the damage that goes to the pickaxe when they mine ore or precious blocks
# If you have any questions, visit http://dev.bukkit.org/server-mods/goldtools/
source:
  item: 266
  amount: 10
disable:
  mine:
    ironore: false
    goldore: false
    lapisore: false
    redstoneore: false
    ironblock: false
    goldblock: false
    lapisblock: false
mine:
  ore:
    tooldamage: 2
  precious:
    tooldamage: 2